warp-ds/react

.releaserc.json

docs: silent the semantic bot

---

CONTRIBUTING.md
README.md

Please feel free to change or add anything. 😄 
I think we are missing a few links to relevant resources, but to what should we have links? 🤷 😅

docs: Add contributing information and update readme

---

.github/workflows/release.yml
.gitignore

Related discussion: https://sch-chat.slack.com/archives/C050N3NQ204/p1682420782915109?thread_ts=1682412782.582729&cid=C050N3NQ204

chore: set node_version to lts/* and pnpm to 8 in GHA

---

packages/index.ts

Include all completed components in the build step

fix: export expandable, box and select from packages/index.ts

---

package.json
packages/toggle/src/component.tsx
packages/toggle/src/item.tsx
pnpm-lock.yaml

The last part of the Toggle component, radio buttons. Buttongroup tokens are used. Styling was migrated from https://github.com/fabric-ds/css/blob/49b07c05686ef132b203026e941bf04dbab6fc7a/src/components/form-elements.css#L201
To test locally: http://localhost:9003/?path=/story/forms-toggle-radiobuttons--multiple-options

fix: radio buttons classes

---

docs/src/Main.tsx
package.json
packages/index.ts
packages/slider/src/component.tsx
packages/slider/stories/Slider.stories.tsx
pnpm-lock.yaml

This PR includes:
- Warpify slider component
- Fix for making it possible to change the slider from outside the component, based on: https://github.com/fabric-ds/react/pull/187 
Design question: Should we remove the `box-shadow` from the thumb when `slider` is disabled? If yes, that will be fixed in `component-classes`

feature(slider): Add slider

---

package.json
packages/button/src/component.tsx
pnpm-lock.yaml

As we will now have a base styling for the anchors we need to make sure that links as buttons won't be affected.
Change for the base styles [here](https://github.com/warp-ds/drive/pull/101)

fix: make sure to style text for links as buttons

---

package.json
packages/combobox/src/component.tsx
packages/index.ts
pnpm-lock.yaml

https://react.fabric-ds.io/combobox

feat: add component classes to the combobox

---

package.json
packages/attention/src/component.tsx
packages/expandable/src/component.tsx
packages/steps/src/component.tsx
packages/steps/src/step.tsx
packages/tabs/src/component-tab.tsx
packages/tabs/src/component-tabs.tsx
pnpm-lock.yaml

Affected components:
attention, tabs, expandable, steps

fix(components): update component classes

---

packages/textarea/src/component.tsx

[WARP-129](https://nmp-jira.atlassian.net/browse/WARP-129): Add placeholder to textarea

fix: add textarea to placeholder

---

.storybook/preview-head.html
index.html
package.json
packages/select/src/component.tsx
pnpm-lock.yaml

[WARP-210](https://nmp-jira.atlassian.net/browse/WARP-210) - Previously, nothing happened on hover or onClick on the chevron. @warp-ds/css component-classes has updated select.chevron to include "pointer-events-none" and "cursor-pointer" which solves the issue. 
Also, update brand css and resets to v1, and add fonts stylesheet

fix(select): fix select chevron

---

.github/workflows/storybook.yml

Previous setup failed but I used npm then.

chore: update workflow for storybook

---

package.json
packages/button/src/component.tsx
packages/button/src/props.tsx
packages/button/stories/Button.stories.tsx
pnpm-lock.yaml

This adds a fullwidth prop to the button component.

fix: Add full width button prop

---

README.md
packages/_helpers/locales/en/messages.po
packages/_helpers/locales/fi/messages.po
packages/_helpers/locales/nb/messages.po
packages/attention/src/locales/en/messages.po
packages/attention/src/locales/fi/messages.po
packages/attention/src/locales/nb/messages.po
packages/attention/stories/Attention.stories.tsx

This should fix the failed synchronize-with-crowdin step that is currently on next. 
After speaking to Christoffer I found out that there's currently a bug in Crowdin, but that they are working on to fix. In the meanwhile I have the updated ReadMe-file with temporary solution to fix this issue.

fix: crowdin build step

---

crowdin.yml
packages/steps/src/locales/en/messages.po
packages/steps/src/locales/fi/messages.mjs
packages/steps/src/locales/fi/messages.po
packages/steps/src/locales/nb/messages.mjs
packages/steps/src/locales/nb/messages.po
packages/steps/src/step.tsx

I guess I forgot to do these changes in https://github.com/warp-ds/react/pull/140

fix: activate translations in steps

---

packages/select/src/locales/fi/messages.mjs
packages/steps/src/locales/fi/messages.mjs
packages/steps/src/locales/nb/messages.mjs
packages/textfield/src/locales/fi/messages.mjs
packages/toggle/src/locales/fi/messages.mjs

After Crowdin PRs with extracted messages are merged, we need to run `pnpm messages:compile` to get the updated messages ready for production.

chore(locales): update translations for select, steps, textfield, toggle

---

packages/tabs/src/component-tabs.tsx

Removing try/catch blocks and improving exception handling in Tabs in an attempt to relieve symptoms described in this thread: https://sch-chat.slack.com/archives/C04P0GYTHPV/p1702545068719299

fix: Improve exception handling in Tabs

---

package.json
pnpm-lock.yaml

Just bumping some deps, most importantly `scroll-doctor`

fix: bump deps

---

packages/slider/src/component.tsx

fix: Slider disabled state fix

---

package.json
packages/card/src/component.tsx
packages/card/stories/Card.stories.tsx
pnpm-lock.yaml

Utilise styling fixes from component classes in the Card component.
https://github.com/warp-ds/react/assets/7531505/4f41aefc-c9c3-4d09-9c7b-218189d6a476

fix: Styling fixes for Card component

---

package.json
pnpm-lock.yaml

This is how the slider behaves after the change:
https://github.com/warp-ds/react/assets/21952706/2fd06711-b132-415e-b0b7-a2704e469d6c

fix: bump core to fix slider

---

packages/tabs/src/component-tabs.tsx
tests/components/TabsTest.tsx
vite.config.js

Add tests for all components within tabs

chore: add tests for tabs

---

packages/steps/src/component.tsx
packages/steps/src/step.tsx
packages/tabs/src/component-tabs.tsx
pnpm-lock.yaml

Depends on https://github.com/warp-ds/css/pull/235

refactor(tabs/steps): rename component classes keys

---

packages/modal/src/component.tsx

This reverts commit 31e5fa3c8d646ccc52963c7c8468ccf3bd1efe1f.

revert: undo PR #318
