warp-ds/react

.storybook/main.cjs, .storybook/preview.js, package.json, packages/alert/src/component.tsx, pnpm-lock.yaml, vite.config.js
We encountered some problems with using common.css where warps uno css and common collided and classes got overriden(border vs border-l-4). Let's revert the usage of this css and revisit it later
=> fix: remove common.css and use safelist

.storybook/main.cjs, package.json, packages/alert/src/component.tsx, pnpm-lock.yaml, vite.config.js
- bump `@warp-ds/component-classes` to `1.0.0-alpha.15` to apply updated styles to the alert icon ([changelog](https://github.com/warp-ds/component-classes/blob/alpha/CHANGELOG.md#100-alpha15-2023-04-05))
- fix class for controlling bottom margin of last child (`last-child:` was renamed to `last:` in @warp-ds/uno)
- don't use pixels in `presetWarp` as we want to default REM values when displaying Warp components. It will cause components to look a bit off compared to fabric components, but that's until we handle typography
=> fix: use updated component-classes in alert component

.github/workflows/release.yml, package.json
Allow the latest version of the package to be imported from eik server without the need to update the version number every time a new bundle version is published.
`https://assets.finn.no/pkg/@warp-ds/react/v1/index.js` 
instead of
`https://assets.finn.no/pkg/@warp-ds/react/v1.0.0-alpha.9/index.js`
More info on aliases in eik can be found [here](https://eik.dev/docs/client_aliases/).
When `1.0.0` version is published to NPM (`alpha` is merged to `main`), the `eik pkg-alias` script should only be run on pushes to `main`, which will be handled in [this task](https://trello.com/c/IfLXuWlg).
=> feat(workflows): add eik aliasing script to release.yml

docs/src/Main.tsx, package.json, packages/_helpers/index.ts, packages/textarea/docs/TextArea.mdx, packages/textarea/src/component.tsx, packages/textfield/src/component.tsx, packages/textfield/stories/Textfield.stories.tsx, pnpm-lock.yaml
Styles were migrated from https://github.com/fabric-ds/css/blob/49b07c05686ef132b203026e941bf04dbab6fc7a/src/components/form-elements.css
For testing in docs:
`http://localhost:3000/textarea`
`http://localhost:3000/textfield`
For testing in Storybook:
`http://localhost:9003/?path=/story/forms-textfield--standard` - check all types
`http://localhost:9003/?path=/story/forms-textarea--standard` - check all types
Design here: https://www.figma.com/file/8P1JQsd82b93gQ6K3igO2p/Warp---Component-library?node-id=393-38455&t=2Rt4QOodGYjj5KNF-0
Old docs: https://react.fabric-ds.io/textfield
=> fix: apply new tokens to textfield and textarea

package.json, packages/button/src/component.tsx, packages/textarea/src/component.tsx, packages/textfield/src/component.tsx, pnpm-lock.yaml
1. Add missing styling for `textarea` https://github.com/fabric-ds/css/blob/49b07c05686ef132b203026e941bf04dbab6fc7a/src/components/form-elements.css#L32
We only add `min-height: 42px;
@media (--min480) {
min-height: 45px; /* height on desktop */
}
` as `resize: vertical` is part of the tw-reset in drive. (classes added [here](https://github.com/warp-ds/component-classes/commit/a3080e11c340a64c883b3c3e43ffb47c53472387))
2. Refactor how we name the component classes on import for button/textfield/textarea
=> fix: add missing classes to textarea and refactor

package.json, packages/select/src/component.tsx, packages/select/stories/Select.stories.tsx, packages/textarea/src/component.tsx, packages/textfield/src/component.tsx, pnpm-lock.yaml
Migrated styling from https://github.com/fabric-ds/css/blob/49b07c05686ef132b203026e941bf04dbab6fc7a/src/components/form-elements.css
- Removed `labelValid` as it only was a color and is now a part of the default label styling
Variant|Screenshot
---|---
Standard | <img width="600" alt="image" src="https://user-images.githubusercontent.com/37986637/233102862-ec14c44d-4757-48b5-a2cf-ea1e7fc20ec6.png">
Hint | <img width="595" alt="image" src="https://user-images.githubusercontent.com/37986637/233102959-7457d024-f3bb-410b-afde-ef11d33d862a.png">
Invalid | <img width="599" alt="image" src="https://user-images.githubusercontent.com/37986637/233103055-dad1f531-7aed-4a1b-9bd7-5dfffa8367e8.png">
Disabled | <img width="630" alt="image" src="https://user-images.githubusercontent.com/37986637/23338644 …
=> fix: add component classes to select

.gitignore, docs/src/plugins/jsxExample.cjs, docs/src/plugins/propTable.cjs, package.json, pnpm-lock.yaml
Both docs and Storybook should work
Test to run:
`pnpm docs:dev` - should work
`pnpm dev` - should also work
=> chore: fix broken docs after vite upgrade

package.json, packages/alert/src/component.tsx, packages/index.ts, pnpm-lock.yaml
Depends on [respective @warp-ds/component-classes changes](https://github.com/warp-ds/component-classes/pull/71) and [last-child class support](https://github.com/warp-ds/drive/pull/110)
=> fix(alert): use imported instead of inline classes

CHANGELOG.md
The changes from 01.06 have not been published after all based on [this error](https://github.com/warp-ds/react/actions/runs/5143061362/jobs/9257606569) so they were also removed.
=> fix(changelog): remove repeated changes

packages/select/src/component.tsx, packages/textfield/src/component.tsx
Fixes an issue described [in this Slack thread](https://sch-chat.slack.com/archives/C04P0GYTHPV/p1686906779445769) where className set on `Select` or `TextField` would override the whole `className` prop of the `input` element.
Also added support for styling the whole component with `style` prop, as it seems to have been the strategy for other form components (Select, Textarea)
=> fix(packages): use className and style in TextField and Select

packages/button/src/component.tsx
**Issue**: different padding for small buttons for primary, negative and utility. The height should always be 32px (y padding 8 px) for small buttons including border. Might be better to use same padding for all small buttons and use `box-sizing: border-box` though 🤔 
**Solution:** use correct classes for small buttons.
```
buttonSmall: 'px-16 py-6 text-xs leading-xs', // .button--small
buttonSmallOverride: 'py-8', // .button--small.button--primary, .button--small.button--destructive, .button--small.button--destructive-flat, .button--small.button--order, .button--small.button--quiet
buttonSmallUtility: 'py-7 px-15', // .button--small.button--secondary
```
**Before (Fabric vs Warp):**
**Now (react storybook):**
=> fix: use correct padding for small buttons

packages/button/src/props.tsx
Background: https://sch-chat.slack.com/archives/C04P0GYTHPV/p1688384717329689
It is confusing that the prop is never true by default but the appearance is.
=> fix: secondary button prop is not true by default

package.json, packages/_helpers/clickable.tsx, pnpm-lock.yaml
With this setup @warp-ds/react will be compatible with [tokens](https://assets.finn.no/pkg/@warp-ds/tokens/v1/finn-no.css) currently available in FINN production. After merging this PR and so releasing a new alpha version, we will update [Warp Tech Docs](https://warp-ds.github.io/tech-docs/getting-started/developers/) and suggest the use of this particular version when relying on the above mentioned tokens.
- bump `@warp-ds/uno` to `1.0.0.-alpha.49`
- bump `@warp-ds/component-classes` to `1.0.0.-alpha.115`
Also:
- Fix missing transparent background on buttons in Clickable, Tabs and Button of type "link"
- import classes for Clickable from component-classes
=> fix: stable FINN prod alpha-release

package.json, pnpm-lock.yaml
Fixes line-height issues on small buttons
Before:
After:
=> fix(buttons): bump component-classes to 1.0.0-alpha.116

CHANGELOG.md, package.json
The release job failed in https://github.com/warp-ds/react/actions/runs/5552396928/jobs/10139700126 so we need to trigger it again by:
a) removing the 1.0.0-alpha.38 tag from https://github.com/warp-ds/react/tags
b) reverting the last semantic-release-bot commit: a8afe4e6582bae1c733530557f57baee94511236.
c) setting fix: prefix on the PR title to tell semantic-release we want our changes released.
=> fix: trigger release of 1.0.0-alpha.38

packages/steps/src/step.tsx
Fixes [WARP-128](https://nmp-jira.atlassian.net/browse/WARP-128)
Before:
After:
=> fix(step): hide outer lines on horizontal variant of steps

.github/workflows/release.yml, .github/workflows/update-next.yml, .releaserc.json, CONTRIBUTING.md, README.md
* ci: rename alpha to next
* ci: stop auto-updating aliased versions on push
* docs(contributing.md): change default/prerelease branch to next
* docs(readme.md): rephrase the part about next vs. stable version + fix npm command
=> chore: set next as prerelease branch (#65)

package.json, packages/button/src/component.tsx, packages/button/stories/Button.stories.tsx, packages/pill/stories/Button.stories.tsx, pnpm-lock.yaml
One more try for button refactoring
In this case we add classes specifically for a button with all variants and such.
The code grew a lot. But I hope it is easier to follow and will improve our work when we will debug problems with buttons.
TODO:
~- [ ] Shortcuts (what it is in comments) will be fixed in the css repo~
PR for the classes and shortcuts: https://github.com/warp-ds/css/pull/44
First attempt [here](https://github.com/warp-ds/react/pull/66) but it was too unsafe but it is for sure less code but what is more important here 🤷
=> fix: use new button classes and improve conditions

.github/workflows/storybook.yml
Steps done: 
1. Created the `gh-pages` branch
2. Set the source to target `gh-pages` and selected root folder here https://github.com/warp-ds/react/settings/pages
3. The output of the `pnpm run build-storybook` is pointed out as a folder for static storybook page
So hopefully when this PR is merged we will have our Storybook published here https://warp-ds.github.io/react/
It is now only triggered on the pushes to next but we can also add `main` to the list. Just wanted to test this one out first
=> chore: add workflow for publishing storybook

packages/tabs/src/component-tabs.tsx, packages/tabs/stories/Tabs.stories.tsx
Background: https://sch-chat.slack.com/archives/C04P0GYTHPV/p1694002177060589
Do not break when a child is falsy.
=> fix: add check for children in tabs

packages/button/src/component.tsx
Fixes issues where buttons receiving only modifier props like `small`, `loading`, `quiet` (without any variant prop) weren't applying any classes. The default button variant in such case should be "secondary".
Also renamed `buttonTypes` to `buttonVariants` to align with [Warp Elements API](https://github.com/warp-ds/elements/blob/next/packages/button/index.js#L39) and to avoid confusion with another prop that is called `type`.
Before:
After:
=> fix(button): set secondary variant styles by default

packages/button/src/component.tsx, packages/button/src/props.tsx, packages/button/stories/Button.stories.tsx
Background: https://nmp-jira.atlassian.net/browse/WARP-281
Can be tested by clicking on the following 👇
=> fix: pass onClick to anchor in button component

.github/workflows/crowdin-sync.yml
To avoid the [a bigger amount of code to be added in every repo](https://github.com/warp-ds/vue/pull/65/files#diff-7209abc5864519d00079d00aa93b020b2bc820640edffdc93df1824a2cfc34a7) let's create a reusable workflow and call it to our workflow. We've done something simliar(but a composite action approach) for PR linter to avoid copy pasting the same code everywhere, and it is also easier to maintain in one place
Reusable workflow is created here https://github.com/warp-ds/reusable-workflows
=> chore: reuse the workflow for crowdin sync

crowdin.yml, lingui.config.ts, packages/select/src/component.tsx, packages/select/src/locales/en/messages.mjs, packages/select/src/locales/en/messages.po, packages/select/src/locales/fi/messages.mjs, packages/select/src/locales/fi/messages.po, packages/select/src/locales/nb/messages.mjs, packages/select/src/locales/nb/messages.po, packages/textfield/src/component.tsx, packages/textfield/src/locales/en/messages.mjs, packages/textfield/src/locales/en/messages.po, packages/textfield/src/locales/fi/messages.mjs, packages/textfield/src/locales/fi/messages.po, packages/textfield/src/locales/nb/messages.mjs, packages/textfield/src/locales/nb/messages.po, packages/toggle/src/component.tsx, packages/toggle/src/locales/en/messages.mjs, packages/toggle/src/locales/en/messages.po, packages/toggle/src/locales/fi/messages.mjs, packages/toggle/src/locales/fi/messages.po, packages/toggle/src/locales/nb/messages.mjs, packages/toggle/src/locales/nb/messages.po, packages/toggle/src/props.ts
Optional label in Toggle, TextField and Select will now also show different language versions depending on `lang` attribute of document's html tag.
**Toggle (Finnish):**
**TextField (Finnish, English, Norwegian):**
**Select (Finnish):**
=> fix(forms): localize 'optional' label in forms

packages/_helpers/locales/en/messages.po, packages/_helpers/locales/fi/messages.po, packages/_helpers/locales/nb/messages.po, packages/breadcrumbs/src/locales/fi/messages.po, packages/breadcrumbs/src/locales/nb/messages.po, packages/button/src/locales/en/messages.po, packages/button/src/locales/fi/messages.po, packages/button/src/locales/nb/messages.po, packages/combobox/src/locales/fi/messages.po, packages/combobox/src/locales/nb/messages.po, packages/modal/src/locales/fi/messages.po, packages/modal/src/locales/nb/messages.po, packages/pill/src/locales/fi/messages.po, packages/pill/src/locales/nb/messages.po, packages/textarea/src/locales/fi/messages.po, packages/textarea/src/locales/nb/messages.po
This diff is a result of running `pnpm messages:extract`.
=> chore(locales): update extracted locale files

packages/alert/src/props.tsx, packages/alert/stories/Alert.stories.tsx
Fixes issues mentioned in [Warp-319](https://nmp-jira.atlassian.net/browse/WARP-319)
Stories are now grouped in the following way:
- all variants with and without interactive content
- expandable example with default role="alert" (for screen reader testing)
- expandable example with role="alert" on a descendant element (for screen reader testing)
Additional examples come from [./alert/docs/Alert.mdx](https://github.com/warp-ds/react/blob/next/packages/alert/docs/Alert.mdx).
=> docs(alert): fix accessibility issues and add more examples to stories

packages/modal/src/component.tsx, packages/modal/stories/Modal.stories.tsx
Background: https://nmp-jira.atlassian.net/jira/software/projects/WARP/boards/15?label=web&selectedIssue=WARP-321
Fixes in the component: 
- exchange `p` with `h1`
- if close button - set focus on it instead of the first interactive element. This change needs to be reflected in the docs. See 👇 
Fixes in stories:
- focus on the "Open modal" button
- reset checked on modal close
- initial focus visible
=> fix: ay11 fixes for the Modal component and affected stories

packages/textarea/src/component.tsx
Background: https://nmp-jira.atlassian.net/jira/software/projects/WARP/boards/15?label=web&selectedIssue=WARP-336
Before|After
---|---
=> fix: connect helptext to text area

packages/button/src/component.tsx
Background: https://nmp-jira.atlassian.net/jira/software/projects/WARP/boards/15?selectedIssue=WARP-331
=> fix: a11y fixes for button link and link as buttons

.storybook/preview-head.html, package.json, packages/button/stories/Button.stories.tsx, pnpm-lock.yaml
- update @warp-ds/css to 1.1.2 to make full-width link (anchor) styled as Button have centered text (Fixes [WARP-347](https://nmp-jira.atlassian.net/browse/WARP-347))
- update @warp-ds/icons to 1.1.0 to fix translations in svg titles
- default doc site language to English
=> fix: anchor text alignment & icon translations

packages/tabs/stories/Tabs.stories.tsx
Background: https://nmp-jira.atlassian.net/jira/software/projects/WARP/boards/15?label=web&selectedIssue=WARP-330
More related background 👇 
```
When a link automatically opens a new window or tab, it can be disorienting, especially for people who have difficulty visually perceiving content and for users with certain cognitive disabilities.
If a link opens a new tab or window without warning, people who are blind or visually impaired and use a screen reader to navigate will likely not realize that a new window or tab has opened and, as a result, will not know where they are and how to get back to the previous page.
```
We remove bad practice from our story.
=> chore: remove bad practice of opening in the new window in the Tabs story

packages/breadcrumbs/src/component.tsx
- Fixed the double Aria label
- Removed the aria-hidden from seperators
This component assumes there is only one Breadcrumb on any single page. We should prob. not make assumptions like this anymore in any of or components and perhaps look into as separate tasks: 
- Random key gen all(?) ID's  (as in moving/modernizing this <code>@warp-ds/elements/packages/utils/index.js</code> <code>generateRandomId()</code> to a broader warp toolbox )
- Accept a root heading level if supplied to the component (we prob need to modernize the <code>unstyled-heading.js</code> script for this)
=> fix: warp-327 Accessability pass

lingui.config.ts, packages/steps/src/component.tsx, packages/steps/src/locales/en/messages.mjs, packages/steps/src/locales/en/messages.po, packages/steps/src/locales/fi/messages.po, packages/steps/src/locales/nb/messages.po, packages/steps/src/step.tsx
Background: https://nmp-jira.atlassian.net/jira/software/projects/WARP/boards/15?label=web&selectedIssue=WARP-329
=> fix: add a11y attributes for to define steps in more accessible way

package.json, packages/expandable/src/component.tsx, packages/expandable/src/props.tsx, packages/expandable/stories/Expandable.stories.tsx, pnpm-lock.yaml
Fix a11y issues for expandable component in [WARP-326](https://nmp-jira.atlassian.net/browse/WARP-326) :
- Switch between ChevronDownIcon and ChevronUpIcon depending on if expanded is set to true or not. This will set the correct svg-title for the icons. 
- Move Icon in the "Box With Custom Icon" story to after the text.
- Add a comma with sr-only to add a pause between the text and the svg-title for screen readers.
- Change text "I am expandable" to a `<h2>` instead of a `<h1>`
=> fix: a11y issues for expandable

crowdin.yml, lingui.config.ts
Together with changes from https://github.com/warp-ds/react/pull/154 `/_helpers` need to be removed from crowdin.yml and lingui.config.ts.
=> chore: don't track _helpers for new translations

packages/textfield/src/component.tsx
Fixes [WARP-337](https://nmp-jira.atlassian.net/browse/WARP-337)
The prefix should be announced before the input, and suffix - after the input.
Inspected input with prefix and suffix button with correct semantic order
=> fix(textfield): render prefix before input

packages/combobox/stories/Combobox.stories.tsx, packages/textfield/stories/Textfield.stories.tsx
Fixes [WARP-337](https://nmp-jira.atlassian.net/browse/WARP-337)
Previously the `clear` and `search` Affix button would be announced using its icon's title, which describes the appearance of the icon. However, to satisfy the regulations, the Affix button’s aria-label should describe the purpose of the button, i.e. "Clear text", "Search". A11y team doesn't agree with this and says that we should rather describe its appearance, but Uu-tilsynet’s regulations trump those personal views.
In this PR we pass respective `aria-labels` to Affix components that render as buttons with icons. This means icons title will not be announced, but just the provided aria-label.
=> docs(affix): add missing aria-labels to Affixes that render as buttons

package.json, pnpm-lock.yaml
@warp-ds/css v1.4.1 introduces the following fixes:
- **expandable**: fix long titles overflowing chevron (https://github.com/warp-ds/css/issues/89) ([9de1b4c](https://github.com/warp-ds/css/commit/9de1b4cc1bd28620fefb6f30e58acfd20d7c4119))
- **expandable**: Only show focus indicator in Expandable component on focus-visible (https://github.com/warp-ds/css/issues/84) ([ccf30f2](https://github.com/warp-ds/css/commit/ccf30f2f9e20a93477cc7f5cf9dc602293320fc6))
- **tabs**: left align all tabs instead of stretch ([9b88498](https://github.com/warp-ds/css/commit/9b884986a0cff63f4e5dbd6fb8c2561331989291))
- **modal**: Z-index of Modal backdrop should be 30 according to css docs (https://github.com/warp-ds/css/issues/90) ([436b9d0](https://github.com/warp-ds/css/commit/436b9d0e5970eff412740d57585179 …
=> chore(deps): update @warp-ds/css to 1.4.1

packages/textfield/src/component.tsx, packages/textfield/stories/Textfield.stories.tsx
Fixes [WARP-374](https://nmp-jira.atlassian.net/browse/WARP-374)
Prefix is an absolutely positioned component and the gap between that component and the `input`'s content is handled using a left padding on the `input`. It’s currently hard-coded to 40px, but with this quick fix we can let users change it by setting a CSS variable in `TextField`’s class (`<TextField class=”[--w-prefix-wdith: 100px]”>`). It’s not dynamic and users will need to calculate how much padding their input needs, but it’s the only non-breaking quick fix we managed to come up with. We should really consider rewriting these form components completely to properly approach styling of different text fields, affixes etc.
=> fix(textfield): allow styling input's left padding if prefix is wider than 40px

.github/workflows/crowdin-sync.yml
Fixes [WARP-418](https://nmp-jira.atlassian.net/browse/WARP-418)
This PR uses the following features of our [reusable crowdin-sync workflow](https://github.com/warp-ds/reusable-workflows)
1. Set a default Crowdin PR reviewer for this repo
2. Forward Crowdin PR comments to Crowdin translators. Unfortunately, the translators won't be able to respond to our comments directly in the PR due to the fact that they are using schibsted enterprise email accounts in Crowdin + Github, and those cannot be added to a public GH organisation. Still, this one-way communication may prove useful when we spot typos or other mistakes in the suggested changes.
=> chore(crowdin sync): use new features

meta.json, package.json, packages/card/src/component.tsx, pnpm-lock.yaml
Fixes [WARP-430](https://nmp-jira.atlassian.net/browse/WARP-430)
Background color of a on-flat Card will no longer be inherited from the parent container.
Before:
After:
=> fix(card): set default background on unselected non-flat card

package.json, pnpm-lock.yaml
This fixes the issue described [here](https://sch-chat.slack.com/archives/C04P0GYTHPV/p1706196986729539).
The library is getting a major bump because CJS support is dropped - but that should be fine since NMP has standardized on ESM - otherwise there are no breaking changes.
=> fix: bump scroll-doctor lib to fix modal issue with scrollbars

packages/modal/src/component.tsx, packages/modal/src/props.ts, packages/modal/stories/Modal.stories.tsx
This will align Vue and React Modal's API, as well as solve a problem where it wasn't possible to reuse the default back button to go to the previous step in a multi-page Modal.
=> feat(modal): add onLeftClick prop to control left button event-handling

package.json, packages/alert/src/component.tsx, packages/alert/stories/Alert.stories.tsx, packages/modal/src/component.tsx, pnpm-lock.yaml
Fixes [WARP-498](https://nmp-jira.atlassian.net/browse/WARP-498)
This PR updates @warp-ds/icons dependency to 2.0.0 and replaces deprecated icons with the [suggested equivalents](https://warp-ds.github.io/tech-docs/components/icons/#deprecated-icons):
=> fix: rename deleted icons after @warp-ds/icons update to 2.0.0

packages/pagination/src/CurrentPage.tsx, packages/pagination/src/Page.tsx, packages/pagination/src/PrevPage.tsx, tests/components/PaginationTest.tsx, vite.config.js
We are aiming at adding unit tests to all components and having test coverage at 100%. This PR does that for Pagination component.
- added tests erroneous states
- removed redundant safeguards for prop values lower than 1 (`usePagination()` hook always sets page number values to at least 1)
- set a `skipFull` flag to `true` to not show test coverage of components that are already at 100% (reduces noise)
=> test(pagination): add tests to get 100% coverage

packages/utils/src/useId.ts
With this PR, the provided fallback ID is also returned when `React.useId` is not supported. This is the case for React v17.
=> fix(useId): return fallback ID for React v17

packages/modal/src/component.tsx
This change fixes a problem with the page scroll remaining locked when the modal component is unmounted before it is closed. This can happen if the host is conditionally rendering the modal.
=> fix(modal): cleanup scroll lock when modal component unmounts

package.json, packages/_helpers/dead-toggle.tsx, packages/toggle/src/component.tsx, packages/toggle/src/props.ts, packages/toggle/stories/Checkbox.stories.tsx, packages/toggle/stories/Radio.stories.tsx, packages/toggle/stories/RadioButtons.stories.tsx, pnpm-lock.yaml, tests/components/ToggleTest.tsx
Depends on
-  https://github.com/warp-ds/css/pull/176
Fixes [WARP-506](https://nmp-jira.atlassian.net/browse/WARP-506)
With these changes our Toggle component will no longer apply classes that control the same CSS property on one element (`input` or `label`). As a result, Toggle should have correct style in different states.
As an addition, `disabled` state handling was restored. This way we align the component with Vue Toggle and the design.
| Finn    | Tori |
| -------- | ------- |
| <img width="187" alt="Screenshot of checkboxes in indeterminate, checked and unchecked state (Finn theme)" src="https://github.com/warp-ds/css/assets/41303231/42bf1752-372e-48df-a2bc-fa5be46549cd">  | <img width="195" alt="Screenshot of checkboxes in indeterminate, checked and unchecked state (Tori theme)" …
=> fix(toggle): fix styling in different states

package.json, packages/select/src/component.tsx, packages/select/stories/Select.stories.tsx, packages/textarea/src/component.tsx, packages/textarea/stories/TextArea.stories.tsx, packages/textfield/src/component.tsx, packages/textfield/stories/Textfield.stories.tsx, packages/toggle/src/component.tsx, packages/toggle/stories/Checkbox.stories.tsx, pnpm-lock.yaml, tests/components/ToggleTest.tsx
Fixes [WARP-515](https://nmp-jira.atlassian.net/browse/WARP-515)
Changes based on the [Figma component library](https://www.figma.com/file/oHBCzDdJxHQ6fmFLYWUltf/Warp---Components-2.0?type=design&node-id=954-37013&mode=design&t=NPcTtpnw8dXLMG36-0):
- label color doesn't change when input is invalid
- label optional should have subtle text color (the other changes to label optional should be handled in a separate task)
- helpText color should be negative when input is invalid
=> fix(forms): use correct colors in label and error text

packages/pagination/src/NextPage.tsx, packages/pagination/src/Page.tsx, packages/pagination/src/Pagination.tsx, packages/pagination/src/PrevPage.tsx, packages/pagination/stories/Pagination.stories.tsx
This will allow teams to decide if they want to have a nofollow rel on pagination component or not. This is an optional prop.
=> feat: Add an optional prop to enable nofollow for pagination component

.github/workflows/i18n.yml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/storybook.yml, package.json, packages/textarea/src/component.tsx, packages/textfield/src/component.tsx, pnpm-lock.yaml, tests/components/TextAreaTest.tsx, tests/components/TextfieldTest.tsx
Use cleaned up input component classes to avoid buggy style overriding when utility classes styling the same CSS properties were applied to the same element
- Update @warp-ds/uno to 1.12.0 in order to handle padding classes with arbitrary values that contain CSS variables (e.g. `pl-[var(--w-prefix-width,_40px)]`
- Use the cleaned up input component classes to avoid style overriding
- Set the pnpm version to v9 in github workflows to avoid lockfile issues after updating pnpm locally
Tested with TextField and TextArea.
=> fix(textfield/textarea): clean up classes

package.json, packages/tabs/src/component-tab.tsx, packages/tabs/src/component-tabs.tsx, pnpm-lock.yaml
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the Tabs component.
Additionally, this PR fixes [WARP-488](https://nmp-jira.atlassian.net/browse/WARP-488) by restoring a bottom border of subtle gray for the whole Tabs wrapper.
Tested the changes by pointing the @warp-ds/css dependency to a feature branch that contains the necessary changes
=> fix(tabs): clean up classes

packages/slider/src/component.tsx, packages/slider/src/props.ts, packages/slider/stories/Slider.stories.tsx
This PR adds a new prop to the Slider component that triggers a callback after moving the slider has ended. The motivation behind this change is to perform state updates only after the user is done moving the slider, and not continuously while the slider is being dragged.
A use case for this behaviour is searching with an updated slider value. The search should only be performed for the final slider value, and not for every intermediate value.
=> feat: slider onChangeAfter prop

packages/select/src/component.tsx, packages/select/src/props.tsx, packages/select/stories/Select.stories.tsx
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the Select component.
Additionally this PR has added missing props `disabled` and `readOnly` to `props.tsx` file for Select and added a missing Select story for `readOnly`. This PR also adds a `handleKeyDown()` function to disable `space`, `arrowUp` and `arrowDown` for when `readOnly` prop is set to `true`
Either link this branch with @warp-ds/css (`fix/clean-up-select-classes` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/clean-up-select-classes`
=> fix(select): clean up classes

.github/workflows/i18n.yml, .github/workflows/lint.pr.yaml, .github/workflows/preview.yml, .github/workflows/release.yml, .github/workflows/storybook.yml, .storybook/preview-head.html, package.json, packages/box/src/component.tsx, packages/box/src/props.tsx, packages/box/stories/Box.stories.tsx, packages/card/src/component.tsx, packages/card/src/props.tsx, packages/switch/src/component.tsx, packages/textarea/src/component.tsx, packages/textarea/src/props.ts, packages/textfield/src/component.tsx, packages/textfield/src/props.ts, pnpm-lock.yaml, tests/components/BoxTest.tsx, tests/components/CardTest.tsx
**Changes:**
- Remove deprecated `clickable` prop from `Box` component, the clickable examples in `Box.stories.tsx` and tests for clickable box in `BoxTest.tsx`.
- Remove deprecated `ccBox.infoClickable`, `ccBox.neutralClickable` and `ccBox.borderedClickable` classes from `Box` component
- Remove deprecated `switch` class from `Switch` component
- Remove deprecated `error` prop from `TextField` and `TextArea` components
- Remove deprecated `onClick` prop from `Card` component and its tests in `CardTest.tsx` file
- Update `@warp-ds/css` dependency to `2.0.0-next.4` and make it also into a peerDependency
- Bump `pnpm/action-setup@v2` to `pnpm/action-setup@v4`
- Bump stylesheet to v2
=> fix: remove deprecated classes

package.json, packages/steps/src/component.tsx, packages/steps/src/step.tsx, tests/components/StepsTest.tsx, tests/components/__snapshots__/StepsTest.tsx.snap
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Step` and `Steps` components.
**Changes:**
- Renamed classNames in `Step` and `Steps` components.
Either link this branch with @warp-ds/css (`fix/cleanup-steps-classes` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/cleanup-steps-classes`
=> fix: clean up step and steps classes

packages/combobox/src/component.tsx, pnpm-lock.yaml, tests/components/ComboBoxTest.tsx
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Combobox` component.
**Changes:**
- Renamed classNames in `Combobox` component.
- Moved all of option-related classes to a `optionClasses` function instead
- Created `ComboboxTest.tsx` file and added tests
Either link this branch with @warp-ds/css (`fix/cleanup-combobox-classes` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/cleanup-combobox-classes`
=> fix(combobox): clean up classes and add tests

packages/slider/src/component.tsx, pnpm-lock.yaml, tests/components/__snapshots__/SliderTest.tsx.snap, tests/components/__snapshots__/StepsTest.tsx.snap
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Slider` component.
**Changes:**
- Renamed classNames in `Slider` component.
- Use new class `activeTrackEnabled`
- Refactored `Slider` component
Either link this branch with @warp-ds/css (`fix/cleanup-slider-classes` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/cleanup-slider-classes`
=> fix(slider): clean up classes

packages/expandable/src/component.tsx, packages/expandable/src/props.tsx, packages/expandable/stories/Expandable.stories.tsx
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Expandable` component.
**Changes:**
- Renamed classNames in `Expandable` component.
- Refactored `Expandable` component
- Remove deprecated `info` prop
- Replace `paddingTop` with `contentWithTitle`
Either link this branch with @warp-ds/css (`fix/cleanup-expandable-component` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/cleanup-expandable-component`
=> fix(expandable): clean up classes

packages/card/src/component.tsx, pnpm-lock.yaml, tests/components/CardTest.tsx
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Card` component.
**Changes:**
- Refactor classes in `Card` component
- Replace `ccCard.card` with `ccCard.base`
Either link this branch with @warp-ds/css (`fix/cleanup-card-classes` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/cleanup-card-classes`
=> fix(card): clean up classes

packages/button/src/component.tsx
- Move variant check to classNames function call (follows the same pattern as in Elements and Vue)
- fix style of buttons with only `href` prop
=> fix(button): refactor and fix variant classes

packages/switch/src/component.tsx, packages/switch/src/props.tsx, packages/switch/stories/Switch.stories.tsx, pnpm-lock.yaml, tests/components/SwitchTest.tsx
This PR ensures no classes styling the same CSS properties are being set on the same HTML element in the `Switch` component.
**Changes:**
- Refactor classes in `Switch` component
- Remove `switchFocus` since those classes have been moved to `ccSwitchToggle.base` in component-classes
- Add missing `disabled` prop and disabled classes to align with Figma and Vue
- Add additional tests to test for disabled state
Either link this branch with @warp-ds/css (`fix/cleanup-switch-toggle-classes` branch) or replace this for @warp-ds/css dependency in package.json: `github:warp-ds/css#component-classes-cleanup` with this  `github:warp-ds/css#fix/cleanup-switch-toggle-classes`
=> fix(switch): clean up classes

packages/badge/src/props.tsx, packages/badge/stories/Badge.stories.tsx
The notification variant of `Badge` is no longer supported in Warp and a corresponding token was removed from @warp-ds/css v2.0.0. This PR removes "notification" variant from `BadgeProps` interface and cleans up Storybook examples.
=> fix(badge): remove deprecated 'notification' example

lingui.config.ts, packages/attention/src/locales/da/messages.po, packages/attention/src/locales/en/messages.po, packages/attention/src/locales/fi/messages.po, packages/attention/src/locales/nb/messages.po
Since we had 2 includes writing the same path for attention, this resulted in 1 translation becoming commented. This fixes that.
=> fix: lingui config for attention component

package.json, packages/attention/stories/Attention.stories.tsx, pnpm-lock.yaml
Part of fixing JIRA issue: [WARP-607](https://nmp-jira.atlassian.net/browse/WARP-607)
**Changes:**
- Bump to latest version of `@warp-ds/core` to get the recent changes (where padding has been added to the attention-element)
- Remove margin-left from callout examples
- Adjust the distance for `Popover with icon as target element` example to align better
=> fix(attention): bump to latest version of @warp-ds/core dependency

package.json, pnpm-lock.yaml
Fixes [WARP-638](https://nmp-jira.atlassian.net/browse/WARP-638)
Update `@warp-ds/css` to `2.0.1` to get an additional `s-border-selected` in the `tabs.active` component class.
Tab's selected border has so far been styled by a "selection-indicator" `span` of the Tabs component. That span's width and position is calculated based on `getBoundingClientRect()` of the child Tab, and after an animation is finished, the correct Tab gets its bottom border. That way of indicating the selected tab does not work server-side, which led us to the solution suggested in this PR. By setting the bottom border color of the selected Tab to `s-border-selected` whenever it's active, we ensure it's styled correctly regardless of whether JavaScript is enabled or not. The animation of the span will remain, as …
=> fix(tab): set border on selected tab to fix SSR

package.json
Fixes warnings when installing the latest version of @warp-ds/react:
```bash
 WARN  Issues with peer dependencies found
.
├─┬ @warp-ds/react 2.0.2
│ └── ✕ unmet peer @warp-ds/css@2.0.0: found 2.0.1
```
=> fix(packages): set @warp-ds/css peer-dependency to 2.0.1

packages/attention/src/component.tsx
Fixes Jira issue: [WARP-651](https://nmp-jira.atlassian.net/browse/WARP-651)
**Changes include:**
- Move `role` and `aria-label` from the `div` wrapping the speech bubble to a `div` that is wrapping the attention `Arrow` component
=> fix(attention): move role and aria-label to attention-arrow wrapper

packages/attention/src/component.tsx, packages/breadcrumbs/src/component.tsx, packages/button/src/component.tsx, packages/combobox/src/component.tsx, packages/modal/src/component.tsx, packages/pagination/src/Pagination.tsx, packages/pill/src/component.tsx, packages/select/src/component.tsx, packages/steps/src/step.tsx, packages/textarea/src/component.tsx, packages/textfield/src/component.tsx, packages/toggle/src/component.tsx
This will ensure that translations are only loaded once, and will not create an infinite render-loop
=> fix(lingui): Move activateI18n outside of components

packages/modal/src/component.tsx
Discovered an error during PR review:
Modal does not import focus lock properly,
fixed this by adding file path
=> fix: update FocusLock import path to include Lock.js

esbuild.js, package.json
Build a version with import mapping pointing to the v19 version of React.
Once this is on Eik we can make an import map for React v19 users.
=> fix: build Eik asset for React 19 users
